name: Run tests
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
    paths: 
      - 'src/**/*'
      - 'test/**/*'
jobs:
  tests:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:16.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: inkless
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Apply migrations to database
        run: dotnet run --project src/Database.Migrator/
      - name: Run tests
        run: dotnet test
