name: Run backend unit tests
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
    paths: 'server/**/*'
jobs:
  tests:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:16.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: inkless
        ports:
          - 5432:5432
    steps:
      - name: Get backend code
        uses: actions/checkout@v4
      - name: Apply migrations to database
        working-directory: ./server
        run: dotnet run --project src/Database.Migrator/
      - name: Run unit tests
        working-directory: ./server
        run: dotnet test
